name: Robot Framework Tests

on:
  push:
    branches:
      - Environment1-Testing

  pull_request:
    branches:
      - Environment1-Testing

jobs:
  robot-tests:

    runs-on: windows-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v2

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Robot Framework tests
        run: |
          robot --outputdir results tests

      - name: Upload Robot Framework results
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: robot-test-results
          path: results/